# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/college_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=space112

# Update the database schema automatically when you change Java code
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (helpful for debugging)
spring.jpa.show-sql=true